name: Deploy Portainer Stack

on:
  push:
    branches:
      - main
    paths:
      - 'openai/main/*'

jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: masluse
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push signaling-server
        uses: docker/build-push-action@v2
        with:
          file: openai/main/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REPOSITORY }}:${{ steps.docker_tags.outputs.tags }}
          platforms: linux/amd64

  deploy:
    needs: build  # Wait for the "build" job to complete
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Portainer Stack
        run: |
          cd /docker/docker-compose/AutomatedDiscovery/
          sudo docker-compose down
          sudo docker-compose pull
          sudo docker-compose up --force-recreate --build -d
