name: Deploy Portainer Stack

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: masluse
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: openai/main/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_REPOSITORY }}:latest
            ${{ secrets.DOCKER_REPOSITORY }}:${{ steps.get_version.outputs.VERSION }}
          platforms: linux/amd64

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Portainer Stack
        run: |
          cd /docker/docker-compose/AutomatedDiscovery/
          sudo docker-compose down
          sudo docker-compose pull
          sudo docker-compose up --force-recreate --build -d
